### ISSUE TITLE
Feature Request: Remove 'Failed to get start location' Warning in Spew

### ISSUE THREAD

**Issue by IrateRedKite** [CallumDev/flplusplus#2]
Vanilla Freelancer always generates the following line of spew on loading the game:

`E:\FL\Scratch\Source\Client\Gf\LocationController.cpp(1029) : *** WARNING: Failed to get start location`

When debugging this line has no value and can be quite confusing to people trying to work out why their client crashed for the first time.

**Comment by CallumDev** [comment]
Added in #4
